runtime: nodejs20 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "bot-app"

handlers:
- url: /components
  static_dir: components

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto